### ISSUE TITLE
Phonenumber from Liechtenstein

### ISSUE THREAD

**Issue by chnuessli** [elektrolytmangel/defikarte-form#10]
The regex should accept the format of the country Liechtenstein.
The format is "+423"

Example: +423 222 01 35

**Comment by elektrolytmangel** [comment]
I changed the phonenumber validation to accept all valid phonenumbers containing country codes. Please review the changes on: https://defikarteformapp.z1.web.core.windows.net/

**Comment by chnuessli** [comment]
Test approved!
