### ISSUE TITLE
LI Phone number isn't accepted

### ISSUE THREAD

**Issue by chnuessli** [elektrolytmangel/defikarte-form#14]
A user ont he website reported this bug. he wanted to enter a liechtensteinische phone number what wasn't accepted.
![image](https://github.com/elektrolytmangel/defikarte-form/assets/63254403/578e9ebc-1b0e-473e-a656-47d5ab475d35)

**Comment by elektrolytmangel** [comment]
Problem is actually in the backend. OTW to staging.

**Comment by elektrolytmangel** [comment]
Production build done.
