### ISSUE TITLE
Insert `source` Tag in the form

### ISSUE THREAD

**Issue by chnuessli** [elektrolytmangel/defikarte-form#5]
Background of this request is that many OSM users want proof of the origin of the data. As discussed with the swiss osm board, the source tag should solve many discussions in changesets.

**Comment by elektrolytmangel** [comment]
Should the 'source' tag be field which can be edited by the user, or is a non-visible value containing i.e. 'defikarte.ch'.

**Comment by chnuessli** [comment]
I would suggest that it's a hidden field like this: "local_knowledge, defikarte.ch"
________________________________
Von: Marc Muehlheim ***@***.***>
Gesendet: Sonntag, 25. Dezember 2022 12:12
An: elektrolytmangel/defikarte-form ***@***.***>
Cc: Christian Nüssli ***@***.***>; Author ***@***.***>
Betreff: Re: [elektrolytmangel/defikarte-form] Insert `source` Tag in the form (Issue #5)


Should the 'source' tag be field which can be edited by the user, or is a non-visible value containing i.e. 'defikarte.ch'?

**Comment by elektrolytmangel** [comment]
Added the source tag in the backend, as well as in the frontend. It can be tested on https://defikarteformapp.z1.web.core.windows.net/
Changes can be seen on https://master.apis.dev.openstreetmap.org (username with the changes: 'marc10012test'.
