### ISSUE TITLE
Problem with 075 numbers

### ISSUE THREAD

**Issue by chnuessli** [elektrolytmangel/defikarte-form#9]
rules: { pattern: /^(\+41|0041)\s?(\d{2})\s?(\d{3})\s?(\d{2})\s?(\d{2})$/ },

**Comment by elektrolytmangel** [comment]
Please describe the bug and the expectation.
Currently +41 75 xxx xx xx is supported.

**Comment by chnuessli** [comment]
It's working on the Test system
